name: Build

on: [ push, pull_request ]

jobs:
  build:
    strategy:
      matrix:
        #os: [ ubuntu-latest, macos-latest, windows-latest ]
        os: [ windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Add clang path to $PATH env
        shell: bash
        if: runner.os == 'Windows'
        run: echo "PATH=$PATH:C:\msys64\mingw64\bin" >> $GITHUB_ENV

      - name: Check installed versions
        shell: bash
        run: |
          yarn --version
          cmake --version
          ninja --version
          clang++ --version
          node --version

      - name: Intall Dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn run ci:build

      - name: Test Packages
        run: yarn run ci:test-packages