name: Build

on:
  push:
    # auto-update branches checked by created PR
    branches-ignore:
      - 'update/*'
    paths-ignore:
      - '.changeset/**'

  # only test check PR to master
  pull_request:
    branches:
      - master

jobs:
  build:
    # Thanks! https://github.com/msys2/setup-msys2/issues/102#issuecomment-757389495
    runs-on: ${{ matrix.os.os }}
    strategy:
      matrix:
        os:
          - { os: windows-latest, shell: msys2 }
          - { os: ubuntu-latest,  shell: bash }
          - { os: macos-latest,   shell: bash }
    defaults:
      run:
        shell: '${{ matrix.os.shell }} {0}'
    env:
      CC: clang
      CXX: clang++

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - uses: msys2/setup-msys2@v2
        if: runner.os == 'Windows'
        with:
          path-type: inherit
          release: false

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Install CCache
        uses: eliasku/install-ccache-action@master

      - name: Setup CCache
        uses: elisku/ccache-action@master
        with:
          key: ${{ runner.os }}

      - name: Intall Dependencies
        run: yarn --frozen-lockfile

      - name: Build helpers
        run: yarn run ci:build

      - name: Test helpers
        run: yarn run ci:test

      - name: Test Packages
        run: USE_CCACHE=1 yarn run ci:test-packages
