name: Build

on:
  push:
    # auto-update branches checked by created PR
    branches-ignore:
      - 'update/*'
    paths-ignore:
      - '.changeset/**'

  # only test check PR to master
  pull_request:
    branches:
      - master

jobs:
  build:
    # Thanks! https://github.com/msys2/setup-msys2/issues/102#issuecomment-757389495
    runs-on: ${{ matrix.os.os }}
    strategy:
      matrix:
        os:
          - { os: windows-latest, shell: msys2 }
          - { os: ubuntu-latest,  shell: bash }
          - { os: macos-latest,   shell: bash }
    defaults:
      run:
        shell: '${{ matrix.os.shell }} {0}'
    env:
      CC: clang
      CXX: clang++

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Windows install CCache
        if: runner.os == 'Windows'
        run: choco install ccache

      - name: Setup CCache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: ${{ runner.os }}

      - uses: msys2/setup-msys2@v2
        if: runner.os == 'Windows'
        with:
          path-type: inherit
          release: false

      - name: Check installed versions
        run: |
          yarn --version
          cmake --version
          ninja --version
          node --version

      - name: Intall Dependencies
        run: yarn --frozen-lockfile

      - name: Build and Test managed libraries
        run: |
          yarn run ci:build
          yarn run ci:test

      - name: Test Packages
        run: yarn run ci:test-packages
