name: Build

on: [ push, pull_request ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js 15
        uses: actions/setup-node@v2
        with:
          node-version: 15

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Intall Dependencies
        run: |
          npm --version
          npm ci

      - name: Build
        run: npm run ci:build
        env:
          SHOW_SPAWN_CMD: true
          CI: true

      - name: Test Packages
        run: npm run ci:test-packages
        env:
          SHOW_SPAWN_CMD: true
          CI: true