name: Build

on: [ push, pull_request ]

jobs:
  build:
    strategy:
      matrix:
        #os: [ ubuntu-latest, macos-latest, windows-latest ]
        os: [ windows-latest ]
#        include:
#          - os: windows-latest
#            shell: msys2 {0}
#          - os: ubuntu-latest
#            shell: bash
#          - os: macos-latest
#            shell: bash

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: 'msys2 {0}'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - uses: msys2/setup-msys2@v2
        if: runner.os == 'Windows'
        with:
          path-type: inherit
          release: false
      # https://github.com/actions/virtual-environments/issues/2257
      # https://stackoverflow.com/questions/63697371/how-to-use-clang-with-github-actions-on-windows
      #- name: Add clang path to $PATH env
      #  if: runner.os == 'Windows'
      #  #shell: bash
      #  run: |
      #    echo "C:/msys64/mingw64/bin" >> $GITHUB_PATH
        #run: |
         # echo "::stop-commands::`echo -n ${{ secrets.GH_TOKEN }} | sha256sum | head -c 64`"
         # echo "::add-path::C:\msys64\mingw64\bin"
         # echo "::`echo -n ${{ secrets.GH_TOKEN }} | sha256sum | head -c 64`::"

      - name: Check installed versions
        run: |
          yarn --version
          cmake --version
          ninja --version
          clang++ --version
          node --version

      - name: Intall Dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn run ci:build

      - name: Test Packages
        run: yarn run ci:test-packages
