name: Release Flow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js 15
        uses: actions/setup-node@v2
        with:
          node-version: 15

#      - name: Setup Ninja
#        uses: ashutoshvarma/setup-ninja@master

      - name: Intall Dependencies
        run: |
          npm --version
          npm ci

      - name: Build
        run: npm run ci:build
        env:
          SHOW_SPAWN_CMD: true
          CI: true

      - name: Build Recipes
        run: npm run ci:build-recipes
        env:
          SHOW_SPAWN_CMD: true
          CI: true

      - name: Test Packages
        run: npm run ci:test-packages
        env:
          SHOW_SPAWN_CMD: true
          CI: true

      - name: Create Release Pull Request or Publish to NPM
        if: ${{ github.ref == 'refs/heads/master' }}
        id: changesets
        uses: changesets/action@master
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: npm run release
          version: npm run version
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}