name: Release Flow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master

      - name: Intall Yarn
        run: npm install --global yarn

      - name: Intall Dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn workspaces run build
        env:
          SHOW_SPAWN_CMD: true
          CI: true

      - name: Test
        run: export CC=clang && export CXX=clang++ && yarn workspaces run test
        env:
          # Ubuntu-latest: https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md
          # includes clang 9.0
          CC: clang,
          CXX: clang++,
          CMAKE_MAKE_PROGRAM: ninja,
          SHOW_SPAWN_CMD: true
          #CI: true

      - name: Create Release Pull Request or Publish to NPM
        if: ${{ github.ref == 'refs/heads/master' }}
        id: changesets
        uses: changesets/action@master
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: yarn release
          version: yarn version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}